import { Font } from '@react-pdf/renderer'

// Shared font registration for all PDF slip templates
Font.register({
  family: 'NotoGujarati',
  fonts: [
    { src: '/fonts/NotoSansGujarati-Regular.ttf?v=3', fontWeight: 400 },
    { src: '/fonts/NotoSansGujarati-Bold.ttf?v=3', fontWeight: 700 },
  ],
})

// Dot-matrix printer font for typed slip values.
//
// This is LX310Dot, generated by tools/build-lx310-font.py from the Epson
// 9-pin draft character-generator bitmaps, so a laser-printed PDF matches what
// the LX-310 actually puts on the slip. It replaces Google's Doto Black, which
// was a decorative face of evenly spaced, non-overlapping round dots on a
// square grid — nothing like a real print head, whose dots are 1/60in across
// but step 1/120in, so they overlap and strokes come out scalloped.
//
// The font is monospaced with one em == one 10 CPI cell (1/10 inch), so
// fontSize 7.2pt is exactly 10 CPI. The slips set larger sizes to match the
// scan of each pre-printed form; see DOT_* in fonts.js consumers.
Font.register({
  family: 'DotMatrix',
  src: '/fonts/LX310Dot.ttf?v=5',
})

// No hyphenation for typed values: the printer never breaks a word, it just
// runs to the end of the field. Without this react-pdf can hyphenate a long
// party name mid-word, which never happens on a real slip.
Font.registerHyphenationCallback((word) => [word])

// Art-deco display font (Righteous) for the Jaynath masthead and numerals
Font.register({
  family: 'Deco',
  src: '/fonts/Deco.ttf?v=1',
})
